#!ipxe

# echo ====== INSTALLING WINDOWS PE TO DISK! =======

# console --x 1024 --y 768

echo WinPE installer by Initgoatfs

dhcp

kernel http://192.168.1.1/netboot/wimboot
initrd http://192.168.1.1/netboot/winpe_new/boot.wim      sources/boot.wim || goto fail
initrd http://emddit.github.io/mshta/ipxe/install.bat          startnet.cmd || goto fail
# initrd http://emddit.github.io/mshta/ipxe/winpeshl.ini         winpeshl.ini || goto fail
boot


:fail
sleep 10
shell
goto fail
